In [1]:
from vect_utils import *
import pandas as pd

# Sample DataFrame
data = {
    'text': [
        'The quick brown fox jumps over the lazy dog.',
        'Never gonna give you up, never gonna let you down.',
        'To be or not to be, that is the question.'
    ],
    'text_1': [
        'The quick brown fox jumps over the lazy dog.',
        'Never gonna give you up, never gonna let you down.',
        'To be or not to be, that is the question.'
    ],
    'numeric_column': [42, 17, 23],
    'list_column': [['apple', 'banana', 'cherry'], ['cat', 'dog'], ['sun', 'moon']]
}

df = pd.DataFrame(data)



In [2]:
df

text  \
0       The quick brown fox jumps over the lazy dog.   
1  Never gonna give you up, never gonna let you d...   
2          To be or not to be, that is the question.   

                                              text_1  numeric_column  \
0       The quick brown fox jumps over the lazy dog.              42   
1  Never gonna give you up, never gonna let you d...              17   
2          To be or not to be, that is the question.              23   

               list_column  
0  [apple, banana, cherry]  
1               [cat, dog]  
2              [sun, moon]

In [3]:
import pickle
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Example ColumnTransformer
column_transformer = ColumnTransformer(
    transformers=[
        ('bm25', BM25Transformer(max_features=5), 'text'),
        ('bm42', BM42Transformer(max_features=3), 'text_1'),
        ('mlb', MultiLabelBinarizerTransformer(), 'list_column'),
        ('onehot', OneHotEncoder(), ['numeric_column']),


    ],
    remainder='passthrough'
)

column_transformer.fit_transform(df)

# Save the fitted ColumnTransformer using pickle
with open('column_transformer.pkl', 'wb') as f:
    pickle.dump(column_transformer, f)

In [4]:
# # Load the ColumnTransformer
with open('column_transformer.pkl', 'rb') as f:
    loaded_column_transformer = pickle.load(f)

loaded_column_transformer


ColumnTransformer(remainder='passthrough',
                  transformers=[('bm25', BM25Transformer(max_features=5),
                                 'text'),
                                ('bm42', BM42Transformer(max_features=3),
                                 'text_1'),
                                ('mlb', MultiLabelBinarizerTransformer(),
                                 'list_column'),
                                ('onehot', OneHotEncoder(),
                                 ['numeric_column'])])

In [5]:
loaded_column_transformer.transform(df)

array([[0.        , 0.        , 0.        , 0.71466282, 0.        ,
        0.        , 0.78052583, 0.        , 1.        , 1.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        ],
       [0.        , 2.13466227, 2.13466227, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        ],
       [2.13466227, 0.        , 0.        , 0.48169973, 2.13466227,
        2.28346283, 0.59983327, 2.28346283, 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 1.        ,
        0.        , 1.        , 0.        ]])

In [6]:
a = np.random.rand(3,2)
b = np.random.rand(3,5)
c = np.random.rand(3,10)

In [7]:
a,b,c

(array([[0.13319062, 0.68494634],
        [0.29941258, 0.48069208],
        [0.20733321, 0.36407055]]),
 array([[0.19799945, 0.64536694, 0.65106891, 0.75509319, 0.07481497],
        [0.64410731, 0.86673339, 0.73183445, 0.44533144, 0.46498187],
        [0.36917286, 0.43957338, 0.41772184, 0.97447015, 0.56006003]]),
 array([[0.33689128, 0.43258351, 0.85926414, 0.03218235, 0.78786343,
         0.19465032, 0.64282256, 0.38129231, 0.25173068, 0.21991968],
        [0.53861389, 0.33734578, 0.05144956, 0.31585742, 0.06021903,
         0.32496128, 0.03049245, 0.49921135, 0.85743361, 0.81001848],
        [0.58959402, 0.81709834, 0.99460455, 0.26564184, 0.15877775,
         0.04684251, 0.87900908, 0.25128978, 0.3291165 , 0.9640704 ]]))

In [8]:
misc.stack_vectors_horizontally(a,b,c)[0].shape

(17,)

In [12]:
bm25 = BM25Transformer()
x,y = bm25.rank_documents(df['text'][0],df['text_1'])

Model not fitted. Fitting the model with provided documents...


In [13]:
x, y

(array([[0, 2, 1]], dtype=int64),
 array([[0.90420764, 0.29661975, 0.31765904]]))